=== rlnbpr/bandwidth-on-demand-os/src/main/resources/schemas/InventoryRetrieval.xsd
<?xml version="1.0"?>
<!--

    The owner of the original code is SURFnet BV.

    Portions created by the original owner are Copyright (C) 2011-2012 the
    original owner. All Rights Reserved.

    Portions created by other contributors are Copyright (C) the contributor.
    All Rights Reserved.

    Contributor(s):
      (Contributors insert name & email here)

    This file is part of the SURFnet7 Bandwidth on Demand software.

    The SURFnet7 Bandwidth on Demand software is free software: you can
    redistribute it and/or modify it under the terms of the BSD license
    included with this distribution.

    If the BSD license cannot be found with this distribution, it is available
    at the following location <http://www.opensource.org/licenses/BSD-3-Clause>

-->
<!--
    Inventory schema that defines Inventory xml file.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.ciena.com/XMLSchema/InventoryRetrieval.xsd"
            xmlns:ir="http://www.ciena.com/XMLSchema/InventoryRetrieval.xsd" elementFormDefault="qualified">

    <xsd:complexType name="global">
        <xsd:attribute name="query" type="xsd:string" use="required"/>
        <xsd:attribute name="queryString" type="xsd:string" use="required"/>
        <xsd:attribute name="queryResult" type="xsd:string" use="required"/>
    </xsd:complexType>


	<xsd:complexType name="GeneralBasic">    	
    		<xsd:attribute name="name" type="xsd:string"/>
    		<xsd:attribute name="displayName" type="xsd:string"/>
    		<xsd:attribute name="type" type="xsd:string"/>
    		<xsd:attribute name="status" type="xsd:string"/>
    		<xsd:attribute name="statusChangeTime" type="xsd:string"/>    	
    </xsd:complexType>       
    
    
	<xsd:complexType name="PortDetail">   	
    		<xsd:attribute name="portId" type="xsd:string"/>
            <xsd:attribute name="name" type="xsd:string"/> 
    		<xsd:attribute name="portName" type="xsd:string"/> 
            <xsd:attribute name="displayName" type="xsd:string"/>
    		<xsd:attribute name="description" type="xsd:string"/> 
    		<xsd:attribute name="portType" type="xsd:string"/> 
    		<xsd:attribute name="portMacAddress" type="xsd:string"/> 
    		<xsd:attribute name="autoNeg" type="xsd:string"/> 
    		<xsd:attribute name="portAdminStatus" type="xsd:string"/> 
    		<xsd:attribute name="adminSpeed" type="xsd:string"/> 
    		<xsd:attribute name="adminDuplex" type="xsd:string"/> 
    		<xsd:attribute name="adminFlowCtrl" type="xsd:string"/> 
    		<xsd:attribute name="maxFrameSize" type="xsd:string"/> 
    		<xsd:attribute name="mirrorPort" type="xsd:string"/> 
    		<xsd:attribute name="mirrorIngress" type="xsd:string"/> 
    		<xsd:attribute name="mirrorEgress" type="xsd:string"/> 
    		<xsd:attribute name="uptime" type="xsd:string"/> 
    		<xsd:attribute name="portState" type="xsd:string"/> 
    		<xsd:attribute name="actorAdminKey" type="xsd:string"/> 
    		<xsd:attribute name="protectionPort" type="xsd:string"/> 
    		<xsd:attribute name="portOperStatus" type="xsd:string"/> 
    		<xsd:attribute name="aggMode" type="xsd:string"/> 
    		<xsd:attribute name="aggProtectionRevertState" type="xsd:string"/> 
    		<xsd:attribute name="aggProtectionRevertTimer" type="xsd:string"/> 
    		<xsd:attribute name="operSpeed" type="xsd:string"/> 
    		<xsd:attribute name="operDuplex" type="xsd:string"/> 
    		<xsd:attribute name="operFlowCtrl" type="xsd:string"/> 
    		<xsd:attribute name="portLinkUpDown" type="xsd:string"/> 
    		<xsd:attribute name="TrapState" type="xsd:string"/> 
    		<xsd:attribute name="portGlobalTrapState" type="xsd:string"/> 
    		<xsd:attribute name="portPgid" type="xsd:string"/>     		
    	
    </xsd:complexType>
    
    <xsd:complexType name="BatteryDetail">
    	
    		<xsd:attribute name="batteryStatus" type="xsd:string"/> 
    		<xsd:attribute name="voltageLevel" type="xsd:string"/> 
    		<xsd:attribute name="batteryCondition" type="xsd:string"/> 
    		<xsd:attribute name="powerSource" type="xsd:string"/> 
    	
    </xsd:complexType>
    
    <xsd:complexType name="FanDetail">
    	
    		<xsd:attribute name="fanModuleNum" type="xsd:string"/> 
    		<xsd:attribute name="fanModuleType" type="xsd:string"/> 
    		<xsd:attribute name="fanModuleStatus" type="xsd:string"/> 
    		<xsd:attribute name="fanAvgSpeed" type="xsd:string"/> 
    		<xsd:attribute name="fanCurrentSpeed" type="xsd:string"/> 
    		<xsd:attribute name="fanMinSpeed" type="xsd:string"/> 
    	
    </xsd:complexType>
    
    <xsd:complexType name="FanTrayDetail">
    	
    		<xsd:attribute name="fanTrayID" type="xsd:string"/> 
    		<xsd:attribute name="fanTrayStatus" type="xsd:string"/> 
    		<xsd:attribute name="fanTrayMode" type="xsd:string"/> 
    		<xsd:attribute name="fanTrayNumFans" type="xsd:string"/> 
    		<xsd:attribute name="fanTrayType" type="xsd:string"/> 
    	
    </xsd:complexType>
    
    <xsd:complexType name="PowerSupplyDetail">
    	
    		<xsd:attribute name="powerSupplyNum" type="xsd:string"/> 
    		<xsd:attribute name="state" type="xsd:string"/> 
    		<xsd:attribute name="powerSupplyType" type="xsd:string"/> 
    		<xsd:attribute name="redundantState" type="xsd:string"/> 
    		<xsd:attribute name="powerSupply-Manufacturer" type="xsd:string"/> 
    		<xsd:attribute name="powerSupplySerial-Number" type="xsd:string"/> 
    		<xsd:attribute name="powerSupplyPartNum" type="xsd:string"/>     		
    	
    </xsd:complexType>
    
    <xsd:complexType name="TempSensorDetail">
    	
    		<xsd:attribute name="tempSensorNum" type="xsd:string"/> 
    		<xsd:attribute name="tempSensorCurrentTemp" type="xsd:string"/> 
    		<xsd:attribute name="tempSensorHighTemp-Threshold" type="xsd:string"/> 
    		<xsd:attribute name="tempSensorLowTemp-Threshold" type="xsd:string"/> 
    		<xsd:attribute name="state" type="xsd:string"/> 
    		<xsd:attribute name="tempSensorDescription" type="xsd:string"/> 
    		<xsd:attribute name="tempSensorHighTemp" type="xsd:string"/> 
    		<xsd:attribute name="tempSensorLowTemp" type="xsd:string"/> 
    		<xsd:attribute name="tempSensorID" type="xsd:string"/>     		
    	
    </xsd:complexType>
    
    <xsd:complexType name="TransceiverDetail">    	
    		<xsd:attribute name="xcvrPortID" type="xsd:string"/> 
    		<xsd:attribute name="operState" type="xsd:string"/> 
    		<xsd:attribute name="adminState" type="xsd:string"/> 
    		<xsd:attribute name="identiferType" type="xsd:string"/> 
    		<xsd:attribute name="connectorType" type="xsd:string"/> 
    		<xsd:attribute name="xcvrType" type="xsd:string"/> 
    		<xsd:attribute name="vendorName" type="xsd:string"/> 
    		<xsd:attribute name="vendorOUI" type="xsd:string"/> 
    		<xsd:attribute name="vendorPartNum" type="xsd:string"/> 
    		<xsd:attribute name="serialNum" type="xsd:string"/> 
    		<xsd:attribute name="wavelength" type="xsd:string"/> 
    		<xsd:attribute name="xcvrMfgDate" type="xsd:string"/> 
    		<xsd:attribute name="fiberType" type="xsd:string"/> 
    		<xsd:attribute name="partRev" type="xsd:string"/> 
    		<xsd:attribute name="txEnabled" type="xsd:string"/> 
    		<xsd:attribute name="rxSignalStatus" type="xsd:string"/> 
    		<xsd:attribute name="txFaultStatus" type="xsd:string"/>     	
    </xsd:complexType>
       
    <xsd:complexType name="LinkDetail">    	
    		<xsd:attribute name="aEnd" type="xsd:string"/> 
    		<xsd:attribute name="zEnd" type="xsd:string"/> 
    		<xsd:attribute name="linkDescription" type="xsd:string"/> 
    		<xsd:attribute name="isPhysicalLink" type="xsd:string"/>     	    	
    </xsd:complexType>
    
    <xsd:complexType name="DeviceBasic">
    	<xsd:attribute name="name" type="xsd:string"/>
    	<xsd:attribute name="displayName" type="xsd:string"/>
    	<xsd:attribute name="sysName" type="xsd:string"/>
    	<xsd:attribute name="ipAddress" type="xsd:string"/>
    	<xsd:attribute name="type" type="xsd:string"/>
    	<xsd:attribute name="status" type="xsd:string"/>
    	<xsd:attribute name="statusChangeTime" type="xsd:string"/>
    </xsd:complexType>
    
    <xsd:complexType name="DeviceDetail">    	
    		<xsd:attribute name="chassisBaseMac" type="xsd:string" />
    		<xsd:attribute name="chassisDeviceId" type="xsd:string" />    		 
    		<xsd:attribute name="ChassisPartNumber" type="xsd:string"/>
    		<xsd:attribute name="chassisSerialNumber" type="xsd:string"/>
    		<xsd:attribute name="chassisMfgDate" type="xsd:string" />
    		<xsd:attribute name="chassisParamVersion" type="xsd:string"/>
    		<xsd:attribute name="chassisSysDateTimeAtDisc" type="xsd:string"/>
    		<xsd:attribute name="chassisSysTimeOffsetAtDisc" type="xsd:string"/>
    		<xsd:attribute name="chassisPlatformType" type="xsd:string"/>
    		<xsd:attribute name="chassisPlatformName" type="xsd:string"/>
    		<xsd:attribute name="chassisPlatformDesc" type="xsd:string"/>
    		<xsd:attribute name="chassisNumSlots" type="xsd:string" />
    		<xsd:attribute name="chassisPrimaryCtrlSlots" type="xsd:string"/>
    		<xsd:attribute name="chassisSecondaryCtrlSlots" type="xsd:string"/>
    		<xsd:attribute name="chassisNumFanTrays" type="xsd:string"/>    		 
    		<xsd:attribute name="chassisNumFansPerTray" type="xsd:string"/>
    		<xsd:attribute name="chassisDcPower" type="xsd:string" />
    		<xsd:attribute name="chassisRedundantPower" type="xsd:string"/>
    		<xsd:attribute name="chassisPhysicalPortsMax" type="xsd:string"/>
    		<xsd:attribute name="chassisAggPortsMax" type="xsd:string"/>
    		<xsd:attribute name="chassisVirtualSwitchMax" type="xsd:string"/>
    		<xsd:attribute name="chassisVirtualInterfaceMax" type="xsd:string"/>
    		<xsd:attribute name="chassisIgmpSnoopVlansMax" type="xsd:string"/>
    		<xsd:attribute name="chassisMulticastGrpsMax" type="xsd:string"/>
    		<xsd:attribute name="chassisRstpDomainsMax" type="xsd:string"/>
    		<xsd:attribute name="chassisBladeGlobalPostState" type="xsd:string"/>
    		<xsd:attribute name="chassisBladeHAStandbyMode" type="xsd:string"/>
    		<xsd:attribute name="swMibVersion" type="xsd:string"/>
    		<xsd:attribute name="sysUpTime" type="xsd:string" />
    		<xsd:attribute name="sysContact" type="xsd:string" />
    		<xsd:attribute name="sysLocation" type="xsd:string" />
    		<xsd:attribute name="pbtBridgeMac" type="xsd:string" />
    		<xsd:attribute name="defaultGateway" type="xsd:string" /> 
    		<xsd:attribute name="serialNumber" type="xsd:string" /> 
    		<xsd:attribute name="boardRevision" type="xsd:string" /> 
    		<xsd:attribute name="timestamp" type="xsd:string" /> 
    		<xsd:attribute name="bootCmdFile" type="xsd:string" /> 
    		<xsd:attribute name="bootCfgFile" type="xsd:string" />     	
    </xsd:complexType>
    <xsd:complexType name="BladeBasic">    	
    		<xsd:attribute name="name" type="xsd:string"/>
    		<xsd:attribute name="displayName" type="xsd:string"/>
    		<xsd:attribute name="type" type="xsd:string"/>
    		<xsd:attribute name="status" type="xsd:string"/>
    		<xsd:attribute name="statusChangeTime" type="xsd:string"/>
    		<xsd:attribute name="runningPkgVer" type="xsd:string"/>
    		<xsd:attribute name="installedPkgVer" type="xsd:string"/>     		
            <xsd:attribute name="installedPkgVer1" type="xsd:string"/>    
            <xsd:attribute name="installedPkgVer2" type="xsd:string"/>       	
    </xsd:complexType>

	<xsd:complexType name="BladeDetail">    	
    		<xsd:attribute name="bladeId" type="xsd:string"/>
    		<xsd:attribute name="bladeType" type="xsd:string"/>
    		<xsd:attribute name="bladeOperState" type="xsd:string"/>
    		<xsd:attribute name="bladeAdminState" type="xsd:string"/>
    		<xsd:attribute name="boardDesc" type="xsd:string"/>
    		<xsd:attribute name="bladeModel" type="xsd:string"/>
    		<xsd:attribute name="bladeRedundateState" type="xsd:string"/>
    		<xsd:attribute name="bladeProtectionMode" type="xsd:string"/>
    		<xsd:attribute name="bladeLastRebootReason" type="xsd:string"/>
    		<xsd:attribute name="bladeAdminPostState" type="xsd:string"/>
    		<xsd:attribute name="bladeOperPostState " type="xsd:string"/>
    		<xsd:attribute name="bladeBoardType" type="xsd:string"/>
    		<xsd:attribute name="bladeBoardCapClass " type="xsd:string"/>
    		<xsd:attribute name="bladeBoardName" type="xsd:string"/>
    		<xsd:attribute name="bladeBoardDes " type="xsd:string"/>
    		<xsd:attribute name="bladeNumPorts" type="xsd:string"/>
    		<xsd:attribute name="bladeBootFlashSize" type="xsd:string"/>
    		<xsd:attribute name="bladeProgramRamSize" type="xsd:string"/>
    		<xsd:attribute name="bladePacketRamSize" type="xsd:string"/>
    		<xsd:attribute name="bladeAddressRamSize" type="xsd:string"/>
    		<xsd:attribute name="bladeDaughterCard" type="xsd:string"/>
    		<xsd:attribute name="bladeParamVersion" type="xsd:string"/>
    		<xsd:attribute name="bladeHwVersion" type="xsd:string"/>
    		<xsd:attribute name="bladeMfgDate" type="xsd:string"/>
    		<xsd:attribute name="bladeBaseMAC" type="xsd:string"/>
    		<xsd:attribute name="bladeSerialNumber" type="xsd:string"/>
    		<xsd:attribute name="bladeBoardPartNumber" type="xsd:string"/>
    		<xsd:attribute name="bladeOEM" type="xsd:string"/>
    		<xsd:attribute name="bladeUpTimeAtDisc" type="xsd:string"/>
    		<xsd:attribute name="bladeCpuUtilizationAtDisc" type="xsd:string"/>
    		<xsd:attribute name="bladePostResult" type="xsd:string"/>
    		<xsd:attribute name="bladePoolTotalSize" type="xsd:string"/>
    		<xsd:attribute name="bladePoolFreeSize" type="xsd:string"/>
    		<xsd:attribute name="bladePoolTotalUnusedSize" type="xsd:string"/>
    		<xsd:attribute name="bladeHeapTotal" type="xsd:string"/>
    		<xsd:attribute name="bladeHeapFreeAtDisc" type="xsd:string"/>
    		<xsd:attribute name="bladeHeapUnusedAtDisc" type="xsd:string"/>   	
    </xsd:complexType>
    

	<xsd:complexType name="TopologicalLink">
            <xsd:sequence>
                <xsd:element name="LinkBasic" type="ir:LinkDetail" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="LinkDetail" type="ir:LinkDetail" minOccurs="0" maxOccurs="1"/>                    			
            </xsd:sequence>
    </xsd:complexType>
    
	<xsd:complexType name="TerminationPoint">
		<xsd:sequence>
        <xsd:element name="PortDetail" type="ir:PortDetail" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="PortBasic" type="ir:GeneralBasic" minOccurs="0" maxOccurs="1"/> 
        </xsd:sequence>           			
     </xsd:complexType>

	<xsd:complexType name="EquipmentHolder">
		<xsd:sequence>
        <xsd:element name="BladeBasic" type="ir:BladeBasic" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="BladeDetail" type="ir:BladeDetail" minOccurs="0" maxOccurs="1"/>            			
     	</xsd:sequence>
     </xsd:complexType>

    <xsd:complexType name="Equipment">
    	<xsd:sequence>
        <xsd:element name="FanBasic" type="ir:GeneralBasic" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="FanDetail" type="ir:FanDetail" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="FanTrayDetail" type="ir:FanTrayDetail" minOccurs="0" maxOccurs="1"/>    		
		<xsd:element name="FanTrayBasic" type="ir:GeneralBasic" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="PowerSupplyDetail" type="ir:PowerSupplyDetail" minOccurs="0" maxOccurs="1"/>    			
     	<xsd:element name="PowerSupplyBasic" type="ir:GeneralBasic" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="BatteryDetail" type="ir:BatteryDetail" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="BatteryBasic" type="ir:GeneralBasic" minOccurs="0" maxOccurs="1"/>    		
		<xsd:element name="TempSensorDetail" type="ir:TempSensorDetail" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="TempSensorBasic" type="ir:GeneralBasic" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="TransceiverBasic" type="ir:GeneralBasic" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="TransceiverDetail" type="ir:TransceiverDetail" minOccurs="0" maxOccurs="1"/>		
     	</xsd:sequence>
     </xsd:complexType>

	<xsd:complexType name="ManagedElement">
            <xsd:sequence>
                <xsd:element name="DeviceBasic" type="ir:DeviceBasic" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="DeviceDetail" type="ir:DeviceDetail" minOccurs="0" maxOccurs="1"/>                    			
            </xsd:sequence>
    </xsd:complexType>



    <!--
        The only global element as the document root.
    -->
    <xsd:element name="InventoryResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="global" type="ir:global" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="ManagedElement" type="ir:ManagedElement" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="Equipment" type="ir:Equipment" minOccurs="0" maxOccurs="unbounded"/>    		
    			<xsd:element name="EquipmentHolder" type="ir:EquipmentHolder" minOccurs="0" maxOccurs="unbounded"/>
    			<xsd:element name="TerminationPoint" type="ir:TerminationPoint" minOccurs="0" maxOccurs="unbounded"/> 
    			<xsd:element name="TopologicalLink" type="ir:TopologicalLink" minOccurs="0" maxOccurs="unbounded"/>   			
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== rlnbpr/bandwidth-on-demand-os/src/main/resources/nbi_response.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This XML defines inventory data. -->
<InventoryResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ciena.com/XMLSchema/InventoryRetrieval.xsd"
    xsi:schemaLocation="http://www.ciena.com/XMLSchema/InventoryRetrieval.xsd ">
    <!-- Global Settings -->
    <!-- Default setting of runtimeStatus is Critical -->
    <global query="getResourcesWithAttributes" queryString="type=Port" queryResult="Success" />

    <TerminationPoint>
        <PortDetail actorAdminKey="2049" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="5" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="to Asd001A_5410_01T 5/1" TrapState="null" name="00:03:18:bc:76:00_Port5/1" adminDuplex="0"
            portState="0" adminSpeed="5" operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0"
            uptime="null" autoNeg="0" portLinkUpDown="null" portname="null" portAdminStatus="1" portOperStatus="2"
            porttype="null" portMacAddress="00:03:18:bf:29:61" displayName="remote.5410-02t.asd001a.dcn.surf.net_Port5/1"
            portId="257" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="8" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="1" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="" TrapState="null" name="00:03:18:bc:76:00_Port1/8" adminDuplex="0" portState="0" adminSpeed="4"
            operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0" uptime="null" autoNeg="0"
            portLinkUpDown="null" portname="null" portAdminStatus="2" portOperStatus="3" porttype="null" portMacAddress="00:03:18:d4:aa:08"
            displayName="remote.5410-02t.asd001a.dcn.surf.net_Port1/8" portId="8" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="2050" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="1" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="" TrapState="null" name="00:03:18:bc:76:00_Port2050" adminDuplex="0" portState="0" adminSpeed="1"
            operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0" uptime="null" autoNeg="0"
            portLinkUpDown="null" portname="null" portAdminStatus="1" portOperStatus="2" porttype="null" portMacAddress="00:03:18:bc:76:09"
            displayName="remote.5410-02t.asd001a.dcn.surf.net_Portto-5410_03T" portId="2050" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="260" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="5" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="to Asd001A_3960_03T 9 (via OMX2T 1611)" TrapState="null" name="00:03:18:bc:76:00_Port5/4"
            adminDuplex="0" portState="0" adminSpeed="5" operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null"
            operDuplex="0" uptime="null" autoNeg="0" portLinkUpDown="null" portname="null" portAdminStatus="1"
            portOperStatus="2" porttype="null" portMacAddress="00:03:18:bf:29:64" displayName="remote.5410-02t.asd001a.dcn.surf.net_Port5/4"
            portId="260" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="32" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="1" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="" TrapState="null" name="00:03:18:bb:5a:00_Port1/32" adminDuplex="0" portState="0" adminSpeed="4"
            operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0" uptime="null" autoNeg="0"
            portLinkUpDown="null" portname="null" portAdminStatus="2" portOperStatus="3" porttype="null" portMacAddress="00:03:18:d4:ad:e0"
            displayName="remote.5410-03t.asd001a.dcn.surf.net_Port1/32" portId="32" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="30" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="1" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="" TrapState="null" name="00:03:18:bb:5a:00_Port1/30" adminDuplex="0" portState="0" adminSpeed="4"
            operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0" uptime="null" autoNeg="0"
            portLinkUpDown="null" portname="null" portAdminStatus="2" portOperStatus="3" porttype="null" portMacAddress="00:03:18:d4:ad:de"
            displayName="remote.5410-03t.asd001a.dcn.surf.net_Port1/30" portId="30" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="2050" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="5" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="to Asd001A_5410_03T 5/1" TrapState="null" name="00:03:18:bc:76:00_Port5/2" adminDuplex="0"
            portState="0" adminSpeed="5" operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0"
            uptime="null" autoNeg="0" portLinkUpDown="null" portname="null" portAdminStatus="1" portOperStatus="2"
            porttype="null" portMacAddress="00:03:18:bf:29:62" displayName="remote.5410-02t.asd001a.dcn.surf.net_Port5/2"
            portId="258" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="259" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="5" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="to Asd001A_3960_03T 10 (via OMX1T 1611)" TrapState="null" name="00:03:18:bc:76:00_Port5/3"
            adminDuplex="0" portState="0" adminSpeed="5" operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null"
            operDuplex="0" uptime="null" autoNeg="0" portLinkUpDown="null" portname="null" portAdminStatus="1"
            portOperStatus="2" porttype="null" portMacAddress="00:03:18:bf:29:63" displayName="remote.5410-02t.asd001a.dcn.surf.net_Port5/3"
            portId="259" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="2" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="4" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="to Asd001A_3940_03T 21 (via OMX2T 1471)" TrapState="null" name="00:03:18:bc:76:00_Port1/2"
            adminDuplex="0" portState="0" adminSpeed="4" operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null"
            operDuplex="0" uptime="null" autoNeg="0" portLinkUpDown="null" portname="null" portAdminStatus="1"
            portOperStatus="2" porttype="null" portMacAddress="00:03:18:d4:aa:02" displayName="remote.5410-02t.asd001a.dcn.surf.net_Port1/2"
            portId="2" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="4" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="1" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="" TrapState="null" name="00:03:18:bc:76:00_Port1/4" adminDuplex="0" portState="0" adminSpeed="4"
            operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0" uptime="null" autoNeg="0"
            portLinkUpDown="null" portname="null" portAdminStatus="1" portOperStatus="3" porttype="null" portMacAddress="00:03:18:d4:aa:04"
            displayName="remote.5410-02t.asd001a.dcn.surf.net_Port1/4" portId="4" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="3" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="1" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="" TrapState="null" name="00:03:18:bc:76:00_Port1/3" adminDuplex="0" portState="0" adminSpeed="4"
            operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0" uptime="null" autoNeg="0"
            portLinkUpDown="null" portname="null" portAdminStatus="1" portOperStatus="3" porttype="null" portMacAddress="00:03:18:d4:aa:03"
            displayName="remote.5410-02t.asd001a.dcn.surf.net_Port1/3" portId="3" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="260" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="5" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="to Asd001A_3960_01T 9" TrapState="null" name="00:03:18:bb:5a:00_Port5/4" adminDuplex="0"
            portState="0" adminSpeed="5" operFlowCtrl="0" aggMode="0" portGlobalTrapStateportPgid="null" operDuplex="0"
            uptime="null" autoNeg="0" portLinkUpDown="null" portname="null" portAdminStatus="1" portOperStatus="2"
            porttype="null" portMacAddress="00:03:18:bf:29:d4" displayName="remote.5410-03t.asd001a.dcn.surf.net_Port5/4"
            portId="260" />
    </TerminationPoint>
    <TerminationPoint>
        <PortDetail actorAdminKey="2050" aggProtectionRevertState="0" type="Port" aggProtectionRevertTimer="0"
            operSpeed="5" protectionPort="0" adminFlowCtrlmaxFrameSizemirrorPortmirrorIngressmirrorEgress="null"
            description="to Asd001A_5410_02T 5/2" TrapState="null" name="00:03:18:bb:5a:00_Port5/1" adminDuplex="0"
